name: CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy-Frontend
        run: |
          echo ${GITHUB_REF/refs\/tags\//}
          # sshpass -p ${{ secrets.pw }} ssh root@dhbw-richie.de -o StrictHostKeyChecking=no < ./deploy/deploy-frontend.bash
      - name: Deploy-Backend
        run: |
          echo ${GITHUB_REF/refs\/tags\//}
          # sshpass -p ${{ secrets.pw }} ssh root@dhbw-richie.de -o StrictHostKeyChecking=no < ./deploy/deploy-backend.bash
        # shell: bash
